# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1247, 657)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionPause = QAction(MainWindow)
        self.actionPause.setObjectName(u"actionPause")
        icon = QIcon()
        icon.addFile(u"pause.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPause.setIcon(icon)
        self.actionContinue = QAction(MainWindow)
        self.actionContinue.setObjectName(u"actionContinue")
        icon1 = QIcon()
        icon1.addFile(u"continue.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionContinue.setIcon(icon1)
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        icon2 = QIcon()
        icon2.addFile(u"close.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClose.setIcon(icon2)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.titleLabel = QLabel(self.centralwidget)
        self.titleLabel.setObjectName(u"titleLabel")
        self.titleLabel.setGeometry(QRect(330, 20, 571, 41))
        font = QFont()
        font.setFamily(u"Microsoft YaHei")
        font.setPointSize(18)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(920, 19, 311, 161))
        font1 = QFont()
        font1.setFamily(u"Microsoft YaHei")
        font1.setPointSize(11)
        self.groupBox.setFont(font1)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 151, 31))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(True)
        font2.setWeight(75)
        self.label.setFont(font2)
        self.videotypeLabel = QLabel(self.groupBox)
        self.videotypeLabel.setObjectName(u"videotypeLabel")
        self.videotypeLabel.setGeometry(QRect(160, 30, 141, 31))
        font3 = QFont()
        font3.setPointSize(9)
        font3.setUnderline(True)
        self.videotypeLabel.setFont(font3)
        self.locationurlLabel = QLabel(self.groupBox)
        self.locationurlLabel.setObjectName(u"locationurlLabel")
        self.locationurlLabel.setGeometry(QRect(160, 60, 141, 31))
        self.locationurlLabel.setFont(font3)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 60, 151, 31))
        self.label_2.setFont(font2)
        self.videonameLabel = QLabel(self.groupBox)
        self.videonameLabel.setObjectName(u"videonameLabel")
        self.videonameLabel.setGeometry(QRect(160, 90, 141, 31))
        self.videonameLabel.setFont(font3)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 90, 151, 31))
        self.label_3.setFont(font2)
        self.resolutionLabel = QLabel(self.groupBox)
        self.resolutionLabel.setObjectName(u"resolutionLabel")
        self.resolutionLabel.setGeometry(QRect(160, 120, 141, 31))
        self.resolutionLabel.setFont(font3)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 120, 141, 31))
        self.label_4.setFont(font2)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(920, 180, 311, 131))
        self.groupBox_2.setFont(font1)
        self.trackingmethodLabel = QLabel(self.groupBox_2)
        self.trackingmethodLabel.setObjectName(u"trackingmethodLabel")
        self.trackingmethodLabel.setGeometry(QRect(160, 30, 141, 31))
        self.trackingmethodLabel.setFont(font3)
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 30, 151, 31))
        self.label_5.setFont(font2)
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 90, 151, 31))
        self.label_6.setFont(font2)
        self.fpsLabel = QLabel(self.groupBox_2)
        self.fpsLabel.setObjectName(u"fpsLabel")
        self.fpsLabel.setGeometry(QRect(160, 90, 141, 31))
        self.fpsLabel.setFont(font3)
        self.framenumberLabel = QLabel(self.groupBox_2)
        self.framenumberLabel.setObjectName(u"framenumberLabel")
        self.framenumberLabel.setGeometry(QRect(160, 60, 141, 31))
        self.framenumberLabel.setFont(font3)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 60, 151, 31))
        self.label_7.setFont(font2)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 330, 291, 231))
        self.groupBox_3.setFont(font1)
        self.enableedgeChb = QCheckBox(self.groupBox_3)
        self.enableedgeChb.setObjectName(u"enableedgeChb")
        self.enableedgeChb.setGeometry(QRect(10, 50, 92, 41))
        self.label_10 = QLabel(self.groupBox_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(140, 40, 111, 21))
        self.label_10.setStyleSheet(u"color: rgb(32, 74, 135);\n"
"")
        self.KSpb = QSpinBox(self.groupBox_3)
        self.KSpb.setObjectName(u"KSpb")
        self.KSpb.setGeometry(QRect(170, 70, 48, 26))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 10, 291, 311))
        self.groupBox_4.setFont(font1)
        self.groupBox_6 = QGroupBox(self.groupBox_4)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 30, 271, 181))
        self.timetrickChb = QCheckBox(self.groupBox_6)
        self.timetrickChb.setObjectName(u"timetrickChb")
        self.timetrickChb.setGeometry(QRect(10, 40, 201, 23))
        self.spacetrickChb = QCheckBox(self.groupBox_6)
        self.spacetrickChb.setObjectName(u"spacetrickChb")
        self.spacetrickChb.setGeometry(QRect(10, 70, 201, 23))
        self.detcycleSpb = QSpinBox(self.groupBox_6)
        self.detcycleSpb.setObjectName(u"detcycleSpb")
        self.detcycleSpb.setGeometry(QRect(10, 140, 48, 26))
        self.globaldetcycleSpb = QSpinBox(self.groupBox_6)
        self.globaldetcycleSpb.setObjectName(u"globaldetcycleSpb")
        self.globaldetcycleSpb.setGeometry(QRect(130, 140, 48, 26))
        self.label_8 = QLabel(self.groupBox_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 110, 67, 21))
        self.label_8.setStyleSheet(u"color: rgb(164, 0, 0);\n"
"")
        self.label_9 = QLabel(self.groupBox_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 110, 111, 21))
        self.label_9.setStyleSheet(u"color: rgb(92, 53, 102);\n"
"\n"
"")
        self.groupBox_7 = QGroupBox(self.groupBox_4)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 210, 271, 91))
        self.enabletrtChb = QCheckBox(self.groupBox_7)
        self.enabletrtChb.setObjectName(u"enabletrtChb")
        self.enabletrtChb.setGeometry(QRect(10, 40, 92, 41))
        self.enablefp16Chb = QCheckBox(self.groupBox_7)
        self.enablefp16Chb.setObjectName(u"enablefp16Chb")
        self.enablefp16Chb.setGeometry(QRect(120, 40, 92, 41))
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(320, 70, 581, 491))
        self.groupBox_5.setFont(font1)
        self.videoLabel = QLabel(self.groupBox_5)
        self.videoLabel.setObjectName(u"videoLabel")
        self.videoLabel.setGeometry(QRect(10, 40, 561, 431))
        font4 = QFont()
        font4.setPointSize(9)
        self.videoLabel.setFont(font4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1247, 28))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionContinue)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionClose)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00..", None))
        self.actionPause.setText(QCoreApplication.translate("MainWindow", u"pause", None))
        self.actionContinue.setText(QCoreApplication.translate("MainWindow", u"continue", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"close", None))
        self.titleLabel.setText(QCoreApplication.translate("MainWindow", u"\u9762\u5411\u7269\u8054\u7f51\u5b9e\u65f6\u591a\u76ee\u6807\u8ddf\u8e2a\u5e94\u7528\u7684\u5e76\u884c\u52a0\u901f\u7cfb\u7edf", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u4fe1\u606f", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u7c7b\u578b\uff1a", None))
        self.videotypeLabel.setText(QCoreApplication.translate("MainWindow", u"Uncertain", None))
        self.locationurlLabel.setText(QCoreApplication.translate("MainWindow", u"Uncertain", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u8def\u5f84/\u7f51\u5740\uff1a", None))
        self.videonameLabel.setText(QCoreApplication.translate("MainWindow", u"Uncertain", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u540d\u79f0\uff1a", None))
        self.resolutionLabel.setText(QCoreApplication.translate("MainWindow", u"Uncertain", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u5206\u8fa8\u7387\uff1a", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u5904\u7406\u4fe1\u606f", None))
        self.trackingmethodLabel.setText(QCoreApplication.translate("MainWindow", u"Uncertain", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u591a\u76ee\u6807\u8ddf\u8e2a\u7b97\u6cd5\uff1a", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u5e27\u7387\uff1a", None))
        self.fpsLabel.setText(QCoreApplication.translate("MainWindow", u"Uncertain", None))
        self.framenumberLabel.setText(QCoreApplication.translate("MainWindow", u"Uncertain", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u5e27\u6570\uff1a", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u7aef\u8fb9\u534f\u540c\u52a0\u901f\u9009\u9879", None))
        self.enableedgeChb.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u542f", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u7f51\u7edc\u73af\u5883\u91c7\u6837\u6570", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\u57fa\u7840\u52a0\u901f\u9009\u9879", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"\u65f6\u7a7a\u95f4\u4f18\u5316\u7b56\u7565", None))
        self.timetrickChb.setText(QCoreApplication.translate("MainWindow", u"\u5728\u65f6\u95f4\u7ef4\u5ea6\u4e0a\u8fdb\u884c\u4f18\u5316", None))
        self.spacetrickChb.setText(QCoreApplication.translate("MainWindow", u"\u5728\u7a7a\u95f4\u7ef4\u5ea6\u4e0a\u8fdb\u884c\u4f18\u5316", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u5468\u671f", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c40\u68c0\u6d4b\u5468\u671f", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"\u4f7f\u7528TensorRT\u52a0\u901f\u63a8\u7406\u6846\u67b6", None))
        self.enabletrtChb.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u542f", None))
        self.enablefp16Chb.setText(QCoreApplication.translate("MainWindow", u"\u4f7f\u7528fp16", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\u8ddf\u8e2a\u89c6\u9891", None))
        self.videoLabel.setText(QCoreApplication.translate("MainWindow", u"\u3010\u89c6\u9891\u5f85\u5f55\u5165... ...\u3011", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

